### PR TITLE
Critical dependencies updated - tests pass, UI appears unaffected

### PR DESCRIPTION
**Pull request by dinophile**
Updating dependencies to prepare for AWS migration. Critical tackled first.

### CODE REVIEW

**Comment by lchski** [comment]
Amazing, thanks for this—will take a quick look tomorrow!

**Comment by lchski** [comment]
Pulled a fresh copy of the repo, and switched to this branch, but running into an error upon `npm install`:

```
➜ git clone git@github.com:cds-snc/simplify-privacy-statements-V2.git
Cloning into 'simplify-privacy-statements-V2'...
remote: Enumerating objects: 2437, done.
remote: Counting objects: 100% (289/289), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 2437 (delta 179), reused 269 (delta 163), pack-reused 2148
Receiving objects: 100% (2437/2437), 1.28 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (1508/1508), done.
➜  cd simplify-privacy-statements-V2
➜  git checkout fix-critical-dependencies-updated
Branch 'fix-critical-dependencies-updated' set up to track remote branch 'fix-critical-dependencies-updated' from 'origin'.
Switched to a new branch 'fix-critical-dependencies-updated'
➜  npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated fsevents@1.2.9: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.7: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated har-validator@5.0.3: this library is no longer supported
npm WARN deprecated request-promise@4.2.2: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated formidable@1.2.1: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /Users/lchski/.n/bin/node /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/lchski/.n/bin/node',
npm ERR! gyp verb cli   '/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /Users/lchski/.pyenv/shims/python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /Users/lchski/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/Users/lchski/.n/bin/node" "/Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/lchski/Code/cds/simplify-privacy-statements-V2/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

For reference, I’m running just slightly behind LTS for `node`:

```
➜  node -v
v16.14.0
➜  npm -v
8.3.1
```

**Comment by dinophile** [comment]
@lchski Hi so sorry I missed your comment from Wednesday! Node version is pinned to 10.6.0! I avoided updating it for now, and am just focused on the dependencies so we can get it moved off of Heroku with as few dependabot finger wags as possible! :joy: 

Could you try again with 10.6.x and let me know if it's working for you?

**Review by lchski — APPROVED** [review]
Now that we got the `pandoc` issue sorted, all works well—good to go! (Tested with `node -v 12.4.0`.)

**Pull request closed without merging**
